// Generated by LiveScript 1.6.0
(function(){
  var x$, style;
  x$ = style = document.createElement('style');
  x$.innerHTML = ig.data.style;
  document.getElementsByTagName('head')[0].appendChild(style);
}).call(this);
